version: '3.8'
services:
  aws_lambda_sam_container:
    container_name: anaconda
    build: ./src
    ports:
      - 8888:8888
    volumes:
      - ./src:/opt/notebooks/
    command: /bin/bash -c "/opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root"